platform :ios, '10.0'
 
inhibit_all_warnings!
use_frameworks!
 
target 'WeatherTestApp' do
    pod 'Alamofire', '~> 4.0'
    pod 'AlamofireObjectMapper', '~> 5.0'
    pod 'ObjectMapper'
    pod 'SwiftyJSON'
end

